Retro/Retro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('main.urls', namespace='main')),
    path('', include('users.urls', namespace='users')),
]

Retro/main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.page_home, name='home'),
    path('about/', views.page_about, name='about'),
    path('services/', views.page_services, name='services'),
    path('portfolio/', views.page_portfolio, name='portfolio'),
    path('right-sidebar/', views.page_right_sidebar, name='right-sidebar'),
    path('contact/', views.page_contact, name='contact'),
]

Retro/users/urls.py
from django.urls import path

from users import views

app_name = 'urls'

urlpatterns = [
    path('login/', views.page_login, name='login'),
    path('registration/', views.page_registration, name='registration'),
    path('logout/', views.page_logout, name='logout'),
    path('profile/', views.page_profile, name='profile')
]

Retro/main/models.py
from django.db import models
from django.template.defaultfilters import truncatechars


class ContactRequest(models.Model):
    name = models.CharField(max_length=64, null=False)
    email_id = models.CharField(max_length=64, null=False)
    phone = models.CharField(max_length=32, null=False)
    message = models.TextField(max_length=3000, null=False)

    def __str__(self):
        return f"From: {self.name} | Message: {truncatechars(self.message, 16)}"

Retro/users/models.py
from django.db import models

# Create your models here.

Retro/main/forms.py
from django import forms
from main.models import ContactRequest


class ContactRequestForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class': "form-control",
        'placeholder': "Name",
    }))
    email_id = forms.CharField(widget=forms.TextInput(attrs={
        'class': "form-control",
        'placeholder': "Email ID",
    }))
    phone = forms.CharField(widget=forms.TextInput(attrs={
        'class': "form-control",
        'placeholder': "Phone No.",
    }))
    message = forms.CharField(widget=forms.Textarea(attrs={
        'class': "form-control",
        'placeholder': "Type your message here...",
        'rows': "9",
    }))

    class Meta:
        fields = ('name', 'email_id', 'phone', 'message')
        model = ContactRequest

Retro/users/forms.py
from django.contrib.auth import forms as auth_forms
from django import forms


class AuthenticationForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': "form-control",
        })
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': "form-control",
            'autocomplete': "current-password",
        })
    )


class RegistrationForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': "form-control",
        }),
    )
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': "form-control",
        }),
        required=False,
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': "form-control",
            'required': False,
        }),
        required=False,
    )
    email = forms.CharField(
        widget=forms.EmailInput(attrs={
            'class': "form-control",
        }),
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': "form-control",
        }),
    )
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': "form-control",
        })
    )

Retro/main/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib import messages

from main.forms import ContactRequestForm
from main.models import ContactRequest


def page_home(request):
    context = {
        'title': 'Retro',
    }

    return render(request, 'main/index.html', context)


def page_about(request):
    context = {
        'title': 'About Us',
    }

    return render(request, 'main/about.html', context)


def page_services(request):
    context = {
        'title': 'Services',
    }

    return render(request, 'main/services.html', context)


def page_portfolio(request):
    context = {
        'title': 'Portfolio',
    }

    return render(request, 'main/portfolio.html', context)


def page_right_sidebar(request):
    context = {
        'title': 'Right Sidebar',
    }

    return render(request, 'main/sidebar-right.html', context)


def page_contact(request):
    if request.method == 'POST':
        form = ContactRequestForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Message was sent successfully!')
            return HttpResponseRedirect(request.META['HTTP_REFERER'])
        messages.error(request, 'Something went wrong, please check form data')
    else:
        form = ContactRequestForm()

    context = {
        'title': 'Contact',
        'form': form,
    }

    return render(request, 'main/contact.html', context)

Retro/users/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from users.forms import AuthenticationForm, RegistrationForm


def page_login(request):
    if request.method == 'GET' and request.user.is_authenticated:
        return HttpResponseRedirect(reverse('main:home'))

    if request.method == 'POST':
        form = AuthenticationForm(request.POST)
        if form.is_valid():
            username_or_email = form.cleaned_data['username']
            password = form.cleaned_data['password']
            if "@" in username_or_email:  # We insist on that username can't contain '@' char
                user = authenticate(email=username_or_email, password=password)
            else:
                user = authenticate(username=username_or_email, password=password)

            if user is not None:
                login(request, user)
                messages.success(request, "Welcome!")
                return HttpResponseRedirect(reverse('users:profile'))
            messages.error(request, 'Incorrect username/email or password')
        else:
            messages.error(request, 'Incorrect form data')
    else:
        form = AuthenticationForm()

    context = {
        'title': 'Sign In',
        'form': form,
    }
    return render(request, 'users/signin.html', context)


def page_registration(request):
    if request.method == 'GET' and request.user.is_authenticated:
        messages.get_messages(request)
        return HttpResponseRedirect(reverse('main:home'))

    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['password'] != form.cleaned_data['confirm_password']:
                messages.error(request, 'Passwords do not match')
            elif User.objects.filter(username=form.cleaned_data['username']).exists():
                messages.error(request, 'This username is already registered')
            else:
                User.objects.create_user(
                    username=form.cleaned_data['username'],
                    email=form.cleaned_data['email'],
                    password=form.cleaned_data['password'],
                    first_name=form.cleaned_data['first_name'],
                    last_name=form.cleaned_data['last_name'],
                )
                messages.success(request, 'Registration was successful!')
                return HttpResponseRedirect(reverse('users:login'))
        else:
            messages.error(request, 'Something went wrong. Please check if data is correct')
    else:
        form = RegistrationForm()

    context = {
        'title': 'Sign Up',
        'form': form,
    }
    return render(request, 'users/signup.html', context)


def page_logout(request):
    logout(request)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', reverse('main:home')))


@login_required(login_url='users:login')
def page_profile(request):
    context = {
        'title': request.user.username,
        'user': request.user,
    }
    return render(request, 'users/profile.html', context)

Retro/main/templates/main/about.html
{% extends 'base.html' %}

{% load static %}

{% load display_messages from main_extras %}

{% block content %}
	<header id="head" class="secondary"></header>

	{% display_messages %}

	<!-- container -->
	<div class="container">

		<div class="row">
			
			<!-- Article main content -->
			<article class="col-sm-8 maincontent">
				<header class="page-header">
					<h1 class="page-title">About us</h1>
				</header>
				<h3>Our Company</h3>
				<p><img src="{% static 'assets/images/about.jpg' %}" alt="" class="img-rounded pull-right" width="300" > Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet, consequuntur eius repellendus eos aliquid molestiae ea laborum ex Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet, consequuntur eius repellendus eos aliquid molestiae ea laborum ex quibusdam laudantium voluptates placeat consectetur quam aliquam beatae soluta accusantium iusto nihil nesciunt unde veniam magnam repudiandae sapiente.</p>
				<p>Consectetur adipisicing elit. Eveniet, consequuntur eius repellendus eos aliquid molestiae ea laborum ex quibusdam laudantium voluptates placeat consectetur quam aliquam beatae soluta accusantium iusto nihil nesciunt unde veniam magnam repudiandae sapiente.</p>
				<h3>Company Goals</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet, consequuntur eius repellendus eos aliquid molestiae ea laborum ex quibusdam laudantium voluptates placeat consectetur quam aliquam beatae soluta accusantium iusto nihil nesciunt unde veniam magnam repudiandae sapiente. consequuntur eius repellendus eos aliquid molestiae ea laborum ex quibusdam laudantium voluptates placeat consectetur quam aliquam!</p>
				<h3>Team</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet, consequuntur eius repellendus eos aliquid molestiae ea laborum ex quibusdam laudantium voluptates placeat consectetur quam aliquam beatae soluta accusantium iusto nihil nesciunt unde veniam magnam repudiandae sapiente. voluptate minus illo tenetur sint ab in culpa cumque impedit quibusdam. Saepe, molestias quia voluptatem natus velit fugiat omnis rem eos sapiente quasi quaerat aspernatur quisquam deleniti accusantium laboriosam odio id?</p>
				<h3>Public News</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet, consequuntur eius repellendus eos aliquid molestiae ea laborum ex quibusdam laudantium voluptates placeat consectetur quam aliquam beatae soluta accusantium iusto nihil nesciunt unde veniam magnam repudiandae sapiente., consequuntur eius repellendus eos aliquid molestiae ea laborum ex quibusdam laudantium voluptates placeat consectetur quam aliquam!</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet, consequuntur eius repellendus eos aliquid molestiae ea laborum ex quibusdam laudantium voluptates placeat consectetur quam aliquam beatae soluta accusantium iusto nihil nesciunt unde veniam magnam repudiandae sapiente.</p>
				
			</article>
			<!-- /Article -->
			
			<!-- Sidebar -->
			<aside class="col-sm-4 sidebar sidebar-right">

				<div class="panel">
					<h4>Latest News</h4>
					<ul class="list-unstyled list-spaces">
						<li><a href="">Responsive Design</a><br><span class="small text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi, laborum.</span></li>
						<li><a href="">HTML5, CSS3 and JavaScript</a><br><span class="small text-muted">Consequuntur eius repellendus eos aliquid molestiae ea laborum ex quibusdam</span></li>
						<li><a href="">Bootstrap</a><br><span class="small text-muted">Eveniet, consequuntur eius repellendus eos aliquid molestiae ea</span></li>
						<li><a href="">Clean Template</a><br><span class="small text-muted">Sed, mollitia earum debitis est itaque esse reiciendis amet cupiditate.</span></li>
						<li><a href="">Premium Quality</a><br><span class="small text-muted">Voluptate minus illo tenetur sint ab in culpa cumque impedit quibusdam. Saepe, molestias quia.</span></li>
					</ul>
				</div>
				
						 
				<div class="wrap one-line-heading"><h2 class="line">Testimonials</h2><div class="line-after" style="width: 198px;"></div></div>
				<ul class="testimonials">
					<li><em>“ Adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit.”</em><h4>- Juan Kask / Client</h4></li>
					<li><em>“ Conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit.”</em><h4>- Dmend Gtey / Client</h4></li>
					<li><em>“ Ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit.”</em><h4>- Johner Kires / Client</h4></li>
				</ul> 

			</aside>
			<!-- /Sidebar -->

		</div>
	
	 
	</div>	<!-- /container -->
{% endblock content %}

Retro/main/templates/main/contact.html
{% extends 'base.html' %}

{% load static %}

{% load display_messages from main_extras %}

{% block content %}
	<header id="head" class="secondary"></header>

	{% display_messages %}

	<!-- container -->
	<div class="container">

		<div class="row">
			
			<!-- Article main content -->
			<article class="col-sm-9 maincontent">
				<header class="page-header">
					<h1 class="page-title">Contact us</h1>
				</header>
				
				<p>
					We’d love to hear from you. Interested in working together? Fill out the form below with some info about your project and I will get back to you as soon as I can. Please allow a couple days for me to respond.
				</p>
				<br>
				{% for message in messages %}
					{% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
						<div class="alert alert-success" role="alert">
							{{ message }}
						</div>
					{% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
						<div class="alert alert-danger" role="alert">
							{{ message }}
						</div>
					{% else %}
						<div class="alert alert-primary" role="alert">
							{{ message }}
						</div>
					{% endif %}
				{% endfor %}
					<form method='POST'>
						{% csrf_token %}
						<div class="row">
							<div class="col-sm-12">
								{{ form.name }}<br/>
							</div>
							<div class="col-sm-12">
								{{ form.email_id }}<br/>
							</div>
							<div class="col-sm-12">
								{{ form.phone }}<br/>
							</div>
						</div>
						<div class="row">
							<div class="col-sm-12">
								{{ form.message }}
							</div>
						</div>
						<br>
						<div class="row">
							<div class="col-sm-6">
								<input class="btn btn-action pull-left" type="submit" value="Send message">
							</div>
							<div class="col-sm-6 text-right">
								
							</div>
						</div>
					</form>

			</article>
			<!-- /Article -->
			
			<!-- Sidebar -->
			<aside class="col-sm-3 sidebar sidebar-right">

				<div class="panel contact">
					<h4>Address</h4>
					<ul>
						  <li><i class="fa fa-phone"></i>1-123-345-6789</li>
						  <li><a href="#"><i class="fa fa-envelope-o"></i> contact@webthemez.com</a></li>
						  <li><i class="fa fa-flag"></i>123 Smith Drive, Baltimore, MD 21212</li>
				   </ul> 
				</div>

			</aside>
			<!-- /Sidebar -->

		</div>
	</div>	<!-- /container -->
	
	<section class="container-full top-space">		  
		   <div id="map-canvas" style="width:100%;height:250px;"></div>
	</section>
{% endblock content %}

{% block scripts %}
	{{ block.super }}
	<!-- Google Maps -->
	<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
	<script src="{% static 'assets/js/google-map.js' %}"></script>
{% endblock scripts %}

Retro/templates/_messages.html
{% for message in messages %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
    {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
    {% else %}
        <div class="alert alert-primary" role="alert">
            {{ message }}
        </div>
    {% endif %}
{% endfor %}

Retro/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport"    content="width=device-width, initial-scale=1.0">
<meta name="description" content="Retro - Free Consulting Responsive Website Template">
<meta name="author" content="webThemez.com">
<title>{{ title }}</title>
<link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}">
{% block css %}
	<link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
	<link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css' %}">
	<!-- Custom styles for our template -->
	<link rel="stylesheet" href="{% static 'assets/css/bootstrap-theme.css' %}" media="screen" >
	<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
{% endblock css %}
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
	<script src="{% static 'assets/js/html5shiv.js' %}"></script>
	<script src="{% static 'assets/js/respond.min.js' %}"></script>
	<![endif]-->
</head>
<body>
<!-- Fixed navbar -->
<div class="navbar navbar-inverse navbar-fixed-top headroom" >
	<div class="container">
		<div class="navbar-header"> 
			<!-- Button for smallest screens -->
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
			<a class="navbar-brand" href="{% url 'main:home' %}"><img src="{% static 'assets/images/logo.png' %}" alt="Retro HTML5 template"></a> </div>
		<div class="navbar-collapse collapse">
			{% block navbar %}
			<ul class="nav navbar-nav pull-right">
				<li class="active"><a href="{% url 'main:home' %}">Home</a></li>
				<li><a href="{% url 'main:about' %}">About</a></li>
				<li><a href="{% url 'main:services' %}">Services</a></li>
				<li><a href="{% url 'main:portfolio' %}">Portfolio</a></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						Pages <b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li><a href="{% url 'main:right-sidebar' %}">Right Sidebar</a></li>
						<li><a href="#">Dummy Link1</a></li>
						<li><a href="#">Dummy Link2</a></li>
						<li><a href="#">Dummy Link3</a></li>
					</ul>
				</li>
				<li><a href="{% url 'main:contact' %}">Contact</a></li>
				{% if user.is_authenticated %}
					<li><a class="btn" href="{% url 'users:logout' %}">Logout</a></li>
				{% else %}
					<li><a class="btn" href="{% url 'users:login' %}">Sign In</a></li>
					<li><a class="btn" href="{% url 'users:registration' %}">Sign Up</a></li>
				{% endif %}
			</ul>
			{% endblock navbar %}
		</div>
		<!--/.nav-collapse --> 
	</div>
</div>
<!-- /.navbar --> 

{% block content %}{% endblock content %}

<footer id="footer" class="top-space">
	<div class="footer1">
		<div class="container">
			<div class="row">
				<div class="col-md-5 panel">
					<h3 class="panel-title">Latest News</h3>
					<div class="panel-body">
						<p>Lorem ipsum dolor amet, consectetur adipiscing elit. Aenean leo lectus sollicitudin convallis eget libero. Aliquam laoreet tellus ut libero semper, egestas velit malesuada. Sed non risus eget dolor amet vestibulum ullamcorper. Integer feugiat molestie.</p>
					</div>
				</div>
				<div class="col-md-4 panel contact">
					<h3 class="panel-title">
					Contact Info
					</h4>
					<div class="panel-body">
						<p>Lorem ipsum dolor amet, consectetur adipiscing ipsum dolor.</p>
						<ul>
							<li><i class="fa fa-phone"></i>1-123-345-6789</li>
							<li><a href="#"><i class="fa fa-envelope-o"></i> contact@webthemez.com</a></li>
							<li><i class="fa fa-flag"></i>123 Smith Drive, Baltimore, MD 21212</li>
						</ul>
					</div>
				</div>
				<div class="col-md-3 panel">
					<h3 class="panel-title">Follow Us</h3>
					<div class="panel-body">
						<p class="follow-me-icons"> <a href=""><i class="fa fa-twitter fa-2"></i></a> <a href=""><i class="fa fa-dribbble fa-2"></i></a> <a href=""><i class="fa fa-github fa-2"></i></a> <a href=""><i class="fa fa-facebook fa-2"></i></a> <a href=""><i class="fa fa-youtube fa-2"></i></a> <a href=""><i class="fa fa-pinterest fa-2"></i></a> </p>
					</div>
				</div>
			</div>
			<!-- /row of panels --> 
		</div>
	</div>
	<div class="footer2">
		<div class="container">
			<div class="row">
				<div class="col-md-6 panel">
					<div class="panel-body">
						<p class="simplenav"> 
							<a href="{% url 'main:home' %}">Home</a> | 
							<a href="{% url 'main:about' %}">About</a> | 
							<a href="{% url 'main:services' %}">Services</a> | 
							<a href="{% url 'main:portfolio' %}">Portfolio</a> | 
							<a href="{% url 'main:contact' %}">Contact</a> 
						</p>
					</div>
				</div>
				<div class="col-md-6 panel">
					<div class="panel-body">
						<p class="text-right"> Copyright &copy; 2014. Template by <a href="http://webthemez.com/" rel="develop">WebThemez.com</a> </p>
					</div>
				</div>
			</div>
			<!-- /row of panels --> 
		</div>
	</div>
</footer>


{% block scripts %}
	<!-- JavaScript libs are placed at the end of the document so the pages load faster --> 
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script> 
	<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script> 
	<script src="{% static 'assets/js/headroom.min.js' %}"></script> 
	<script src="{% static 'assets/js/jQuery.headroom.min.js' %}"></script> 
	<script src="{% static 'assets/js/custom.js' %}"></script>
{% endblock scripts %}
</body>
</html>

Retro/users/templates/users/profile.html
{% extends 'base.html' %}

{% load static %}

{% load display_messages from main_extras %}

{% block content %}
	<header id="head" class="secondary"></header>

	<div class="container" style="padding-top: 10px;">
		{% display_messages %}
	</div>

	<div class="container" style="padding-bottom:300px;">
		<h2>Profile</h2>
		<div>
			<strong>Username: </strong>
			<span>{{ user.username }}</span>
		</div>
		<div>
			<strong>E-mail: </strong>
			<span>{{ user.email }}</span>
		</div>
		{% if user.first_name %}
			<div>
				<strong>First name: </strong>
				<span>{{ user.username }}</span>
			</div>
		{% endif %}
		{% if user.last_name %}
			<div>
				<strong>Last name: </strong>
				<span>{{ user.last_name }}</span>
			</div>
		{% endif%}
	</div>
{% endblock %}

Retro/users/templates/users/signin.html
{% extends 'base.html' %}

{% load static %}

{% load display_messages from main_extras %}

{% block content %}
	<header id="head" class="secondary"></header>

	<!-- container -->
	<div class="container">

		<ol class="breadcrumb">
			<li><a href="{% url 'main:home' %}">Home</a></li>
			<li class="active">User access</li>
		</ol>

		<div class="row">
			
			<!-- Article main content -->
			<article class="col-xs-12 maincontent">
				<header class="page-header">
					<h1 class="page-title">Sign in</h1>
				</header>
				
				<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2" style="padding-bottom: 120px;">
					<div class="panel panel-default">
						<div class="panel-body">
							<h3 class="thin text-center">Sign in to your account</h3>
							<p class="text-center text-muted">
								Lorem ipsum dolor sit amet, <a href="{% url 'users:registration' %}">Register</a> adipisicing elit. Quo nulla quibusdam cum doloremque incidunt nemo sunt a tenetur omnis odio. 
							</p>
							<hr>
							<div class="container">
								{% display_messages %}
							</div>
							<form method="POST" action="{% url 'users:login' %}">
								{% csrf_token %}
								<div class="top-margin">
									<label for="{{ form.username.id_for_label }}">Username/Email <span class="text-danger">*</span></label>
									{{ form.username }}
								</div>
								<div class="top-margin">
									<label for="{{ form.password.id_for_label }}">Password <span class="text-danger">*</span></label>
									{{ form.password }}
								</div>

								<hr>

								<div class="row">
									<div class="col-lg-8">
										<b><a href="#">Forgot password?</a></b>
									</div>
									<div class="col-lg-4 text-right">
										<button class="btn btn-action" type="submit">Sign in</button>
									</div>
								</div>
							</form>
						</div>
					</div>

				</div>
				
			</article>
			<!-- /Article -->

		</div>
	</div>	<!-- /container -->
	
{% endblock content %}

Retro/users/templates/users/signup.html
{% extends 'base.html' %}

{% load static %}

{% load display_messages from main_extras %}

{% block content %}
	<header id="head" class="secondary"></header>

	<!-- container -->
	<div class="container">

		<ol class="breadcrumb">
			<li><a href="{% url 'main:home' %}">Home</a></li>
			<li class="active">Registration</li>
		</ol>

		<div class="row">
			
			<!-- Article main content -->
			<article class="col-xs-12 maincontent">
				<header class="page-header">
					<h1 class="page-title">Registration</h1>
				</header>
				
				<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<h3 class="thin text-center">Register a new account</h3>
							<p class="text-center text-muted">
								Lorem ipsum dolor sit amet, <a href="{% url 'users:login' %}">Login</a> adipisicing elit. Quo nulla quibusdam cum doloremque incidunt nemo sunt a tenetur omnis odio. 
							</p>
							<hr>
							<div class="container">
								{% display_messages %}
							</div>
							<form method="POST" action="{% url 'users:registration' %}">
								{% csrf_token %}
								<div class="top-margin">
									<label for="{{ form.username.id_for_label}}">Username <span class="text-danger">*</span></label>
									{{ form.username }}
								</div>
								<div class="top-margin">
									<label for="{{ form.first_name.id_for_label }}">First Name</label>
									{{ form.first_name }}
								</div>
								<div class="top-margin">
									<label for="{{ form.last_name.id_for_label }}">Last Name</label>
									{{ form.last_name }}
								</div>
								<div class="top-margin">
									<label for="{{ form.email.id_for_label }}">Email Address <span class="text-danger">*</span></label>
									{{ form.email }}
								</div>

								<div class="row top-margin">
									<div class="col-sm-6">
										<label for="{{ form.password.id_for_label }}">Password <span class="text-danger">*</span></label>
										{{ form.password }}
									</div>
									<div class="col-sm-6">
										<label for="{{ form.confirm_password.id_for_label }}">Confirm Password <span class="text-danger">*</span></label>
										{{ form.confirm_password }}
									</div>
								</div>

								<hr>

								<div class="row">
									<div class="col-lg-8">
										<label class="checkbox">
											<input type="checkbox" required> 
											I've read the <a href="#!">Terms and Conditions</a>
										</label>                        
									</div>
									<div class="col-lg-4 text-right">
										<button class="btn btn-action" type="submit">Register</button>
									</div>
								</div>
							</form>
						</div>
					</div>

				</div>
				
			</article>
			<!-- /Article -->

		</div>
	</div>	<!-- /container -->
{% endblock content %}